# -*- coding: utf-8 -*-
"""Bản sao của bai-tap-pandas-series.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Anh-Quan-07/0cf8f210710db6ec579c0c710f293350/b-n-sao-c-a-bai-tap-pandas-series.ipynb

Câu 1: Hãy tạo 1 đối tượng kiểu Series có tối thiểu 10 phần tử (kiểu số) với giá trị tùy ý thích của bạn. 
       In giá trị của Series đó ra màn hình
"""

import pandas as pd

a = pd.Series([33,22,78,40,69,82,50,90,56,23])
seri = pd.Series(a)
print(seri)

"""Câu 2: Hãy tạo 1 đối tượng kiểu Series với giá trị khởi tạo hình thành từ dữ liệu kiểu Dictionary. In kết quả ra màn hình"""

import pandas as pd

data = {'a' : 8, 'b' : 43, 'd' : 70, 'f': 11, 'g': 33}
serserii = pd.Series(data,index=['a','c','b','d','e','f'])
print(serserii)

"""Câu 3: Sử dụng series ở câu 1, hãy thay đổi giá trị của cột index từ kiểu số theo kiểu ký tự với giá trị do bạn tự xác định."""

import pandas as pd
index = ['a','b','c','d','e','f','g','h','i','j']
a = [32,35,66,12,56,89,92,74,81,55]
seri11 = pd.Series(a, index=index)
seri11

"""Câu 4: Sử dụng series ở câu 2, hãy truy cập đến phần tử thứ 5 và in ra màn hình"""

pd.DataFrame(serserii).iloc[4]

"""Câu 5: Sử dụng series ở câu 3, hãy truy cập đến 1 phần tử dựa theo chỉ số kiểu ký tự do bạn lựa chọn và in ra màn hình"""

seri11['a']

"""Câu 6: Sử dụng series ở câu 3, hãy tìm ra tính chất đặc thù trong các chỉ số kiểu kí tự, thực hiện vòng lặp for duyệt trên các chỉ mục kiểu kí tự này để lọc ra những phần tử thỏa mãn điều kiện và in ra màn hình"""

seri11[[name.endswith('2') for name in seri11.index]]

"""Câu 7: Sử dụng series ở câu 1, hãy đổi tên cột index thành 'STT' và đặt tên cho series là 'Gia_tri'. In kết quả ra màn hình """

seri.index.name = 'STT'
seri.name = 'Gia_tri'
seri

"""Câu 8: Hãy áp dụng hàm logarith của gói numpy với series ở câu 1 và in kết quả ra màn hình"""

import numpy as np
np.log(seri)

"""Câu 9: Lọc các giá trị của series 1 > 15 và in ra màn hình"""

seri[seri > 15]